// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kumgbetkbyhumpdtktpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bWdiZXRrYnlodW1wZHRrdHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTU3NjYsImV4cCI6MjA2MDg5MTc2Nn0.otvGRqKFq040hZno2PhbBPZzdOkgNWSF2L3IsluQnEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);